name: source_app
description: A gui git to Linux

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
# publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.0.7

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path:
  sembast: ^3.0.0+2
  path_provider: ^2.0.1
  google_fonts: ^2.0.0
  file_chooser:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/file_chooser
      ref: b0794faf2c000576515aee56ca6bb5bee64cece4
  path_provider_fde:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/flutter_plugins/path_provider_fde
      ref: b0794faf2c000576515aee56ca6bb5bee64cece4
  unicorndial: ^1.1.5
  flutter_svg: ^0.21.0-nullsafety.0
  load:
    git:
      url: git://github.com/CaiJingLong/flutter_load_widget.git
      ref: 070a58bb23729c73f3729883a15af9b8edd0b79c
  bot_toast: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/source-logo.png
    - images/logo-grey.png
    - images/delete-repository.png
    - images/branch-local.png
    - images/branch-remote.png
    - images/down-indicator.png
    - images/ic-folder.png
    - images/ic_stash.png
    - images/ic_tags.png
    - images/ic_menu_close.svg
    - images/ic_menu_branch.svg
    - images/ic_menu_commit.svg
    - images/ic_menu_stash.svg
    - images/ic_menu_fetch.svg
    - images/ic_menu_merge.svg
    - images/ic_menu_pull.svg
    - images/ic_menu_push.svg
    - images/file_addeded.svg
    - images/file_conflicted.svg
    - images/file_deleted.svg
    - images/file_modified.svg
    - images/file_renamed.svg
    - images/flow/bottom-left.png
    - images/flow/bottom-right.png
    - images/flow/commit.png
    - images/flow/horizontal.png
    - images/flow/start-commit.png
    - images/flow/end-commit.png
    - images/flow/top-left.png
    - images/flow/top-right.png
    - images/flow/vertical.png
    - images/flow/left-left.png
    - images/flow/right-right.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
