name: source-app
version: 0.0.1
summary: A gui git to Linux
description: Source is a simple client for working with git.
confinement: devmode
base: core18
grade: stable
icon: snap/gui/icon.png


apps:
  source-app:
    command: source_app
    extensions: [flutter-master]
    plugs:
      - network
      - desktop

parts:
  source-app:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart # The main entry-point file of the application